import streamlit as st

# Afirmaciones con lenguaje más neutral y universal
afirmaciones_dia = {
    1: {"mañana": "Mi subconsciente coopera conmigo y responde con precisión a las instrucciones que le doy.",
        "noche": "Cada pensamiento que cultivo crea condiciones a mi favor. Me hago responsable de lo que pienso y siento."},
    2: {"mañana": "Mis palabras y pensamientos son semillas de poder que mi subconsciente transforma en realidades armoniosas y perfectas.",
        "noche": "Cuando pienso con claridad y paz, mi subconsciente responde con acciones constructivas y equilibradas."},
    3: {"mañana": "Reemplazo viejas creencias por ideas nuevas, positivas y llenas de vida que mi subconsciente acepta.",
        "noche": "Dirijo mi mente con intención y mi subconsciente obedece mis pensamientos claros y positivos."},
    4: {"mañana": "Libero toda creencia limitante y dejo espacio para nuevas ideas que reflejan bienestar y confianza.",
        "noche": "Uso un lenguaje consciente y empoderador que impulsa a mi subconsciente a actuar a mi favor."},
    5: {"mañana": "Instalo en mi mente pensamientos de salud, bienestar, abundancia y plenitud que forman mi nueva realidad.",
        "noche": "Mis pensamientos crean mi mundo. Elijo alimentar mi mente con ideas de éxito, bienestar y propósito."},
    6: {"mañana": "Transformo mis palabras para transformar mis experiencias. Elijo hablar con claridad, optimismo y verdad.",
        "noche": "Renuevo mi vida renovando mi forma de pensar. Cada pensamiento positivo me acerca a mi propósito."},
    7: {"mañana": "Deseo lo mejor para los demás, y ese mismo bienestar fluye naturalmente hacia mí.",
        "noche": "Mi mente subconsciente acepta toda idea que repito con convicción. Por eso cultivo pensamientos de bienestar."},
    8: {"mañana": "Tengo acceso a la claridad y tomo decisiones alineadas con lo mejor para mí.",
        "noche": "Selecciono cuidadosamente mis pensamientos, permitiendo solo los que construyen mi bienestar."},
    9: {"mañana": "Fortalezco mi fe a través de la práctica diaria de pensamientos confiados y amables.",
        "noche": "Tengo el poder de elegir pensamientos que me elevan. Elijo vida, amor, salud y claridad."},
    10: {"mañana": "La armonía comienza dentro de mí y se refleja en cada aspecto de mi entorno.",
         "noche": "Nutro mi mente subconsciente con ideas que sanan, expanden y elevan mi consciencia."},
    11: {"mañana": "Elijo soltar el pasado y abro espacio al bienestar, la reconciliación y el crecimiento interior.",
         "noche": "Mi mente subconsciente actúa según las ideas que mantengo con claridad y decisión."},
    12: {"mañana": "Declaro con certeza que mi camino se revela fácilmente y con éxito.",
         "noche": "Transformo todo pensamiento que limita y fortalezco los que me conectan con mi propósito."},
    13: {"mañana": "Mi voz interior tiene el poder de transformar el miedo en confianza.",
         "noche": "Confío en mi intuición. Me guía paso a paso hacia el cumplimiento de mis objetivos."},
    14: {"mañana": "Reconozco la energía vital en todo lo que hago y en cada situación que experimento.",
         "noche": "Incluso mientras descanso, mi subconsciente continúa organizando mi vida hacia el bienestar."},
    15: {"mañana": "Confío en el proceso de la vida. Suelto el control y permito que lo mejor fluya hacia mí.",
         "noche": "Declaro con claridad lo que deseo y lo entrego a mi subconsciente, que actúa mientras duermo."},
    16: {"mañana": "Estoy conectada con la energía de la abundancia. Todo lo que necesito llega a mí con facilidad.",
         "noche": "Mi mente crea lo que imagina. Por eso elijo imágenes mentales llenas de éxito, gratitud y paz."},
    17: {"mañana": "Visualizo mi deseo cumplido y agradezco su realización. Ya está sucediendo.",
         "noche": "Siento la certeza de que mis pensamientos constructivos están dando fruto ahora mismo."},
    18: {"mañana": "Doy gracias por todo lo bueno que ya es parte de mi vida, visible o invisible.",
         "noche": "Al entrar en el descanso, siembro ideas de plenitud, salud y alegría en mi subconsciente."},
    19: {"mañana": "Permanezco firme en mis convicciones. Mi fe es clara, constante y confiada.",
         "noche": "Durante el sueño, mi mente sigue trabajando a favor de mis deseos y aspiraciones más elevadas."},
    20: {"mañana": "Suelto lo que me preocupa y recibo con apertura nuevas soluciones y caminos.",
         "noche": "Me inundo de pensamientos de verdad, alegría, esperanza y claridad antes de dormir."},
    21: {"mañana": "Planto pensamientos positivos en mi mente cada día, y mi realidad florece con ellos.",
         "noche": "Mi subconsciente cuida de mí, reestableciendo equilibrio, salud y bienestar continuo."},
}
